#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat May 15 22:34:43 EDT 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto e4b9689b77c24f7bb82cbf1e9f18f953 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot cpu_tb_behav xil_defaultlib.cpu_tb -log elaborate.log"
xelab -wto e4b9689b77c24f7bb82cbf1e9f18f953 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot cpu_tb_behav xil_defaultlib.cpu_tb -log elaborate.log

