set_property SRC_FILE_INFO {cfile:/home/lambdallama/E341Final/E341Final.srcs/constrs_1/imports/new/lab4constraints.xdc rfile:../../../E341Final.srcs/constrs_1/imports/new/lab4constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16 [get_ports rst]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L16 [get_ports clk]
